// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: replication.proto

package replication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicationUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLSN        uint64                 `protobuf:"varint,1,opt,name=minLSN,proto3" json:"minLSN,omitempty"`
	MaxLSN        uint64                 `protobuf:"varint,2,opt,name=maxLSN,proto3" json:"maxLSN,omitempty"`
	Records       []byte                 `protobuf:"bytes,3,opt,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationUnit) Reset() {
	*x = ReplicationUnit{}
	mi := &file_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationUnit) ProtoMessage() {}

func (x *ReplicationUnit) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationUnit.ProtoReflect.Descriptor instead.
func (*ReplicationUnit) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicationUnit) GetMinLSN() uint64 {
	if x != nil {
		return x.MinLSN
	}
	return 0
}

func (x *ReplicationUnit) GetMaxLSN() uint64 {
	if x != nil {
		return x.MaxLSN
	}
	return 0
}

func (x *ReplicationUnit) GetRecords() []byte {
	if x != nil {
		return x.Records
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastLSN       uint64                 `protobuf:"varint,1,opt,name=lastLSN,proto3" json:"lastLSN,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_replication_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetLastLSN() uint64 {
	if x != nil {
		return x.LastLSN
	}
	return 0
}

var File_replication_proto protoreflect.FileDescriptor

const file_replication_proto_rawDesc = "" +
	"\n" +
	"\x11replication.proto\"[\n" +
	"\x0fReplicationUnit\x12\x16\n" +
	"\x06minLSN\x18\x01 \x01(\x04R\x06minLSN\x12\x16\n" +
	"\x06maxLSN\x18\x02 \x01(\x04R\x06maxLSN\x12\x18\n" +
	"\arecords\x18\x03 \x01(\fR\arecords\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\alastLSN\x18\x01 \x01(\x04R\alastLSN2E\n" +
	"\x12ReplicationService\x12/\n" +
	"\x13SendReplicationUnit\x12\x10.ReplicationUnit\x1a\x04.Ack\"\x00B,Z*github.com/Adarsh-Kmt/DragonDB/replicationb\x06proto3"

var (
	file_replication_proto_rawDescOnce sync.Once
	file_replication_proto_rawDescData []byte
)

func file_replication_proto_rawDescGZIP() []byte {
	file_replication_proto_rawDescOnce.Do(func() {
		file_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_replication_proto_rawDesc), len(file_replication_proto_rawDesc)))
	})
	return file_replication_proto_rawDescData
}

var file_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_replication_proto_goTypes = []any{
	(*ReplicationUnit)(nil), // 0: ReplicationUnit
	(*Ack)(nil),             // 1: Ack
}
var file_replication_proto_depIdxs = []int32{
	0, // 0: ReplicationService.SendReplicationUnit:input_type -> ReplicationUnit
	1, // 1: ReplicationService.SendReplicationUnit:output_type -> Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_replication_proto_init() }
func file_replication_proto_init() {
	if File_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_replication_proto_rawDesc), len(file_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replication_proto_goTypes,
		DependencyIndexes: file_replication_proto_depIdxs,
		MessageInfos:      file_replication_proto_msgTypes,
	}.Build()
	File_replication_proto = out.File
	file_replication_proto_goTypes = nil
	file_replication_proto_depIdxs = nil
}
